### ISSUE TITLE
Icons on the map don't show

### ISSUE THREAD

**Issue by victormandela** [gkaramanis/tidytuesday#5]
Hi there, 

First off, really incredible code and visualization. Some awesome you are doing there and I know it ain't easy!. The code for the deforestation analysis at "2021-week14" doesn't seem to produce the country Icons. Kindly help.

**Comment by gkaramanis** [comment]
Thank you! I restructured the repo some time ago and the path to the icons should have "2020" at the beginning. I have pushed the change, so the code should be working now.

**Comment by victormandela** [comment]
Hey there, 

Thanks for the quick response. The icons still don't show on the graph. See attached screenshot[
![image](https://user-images.githubusercontent.com/89085250/156184777-ad8284e8-4109-4a6e-8305-7c2ee602cc83.png)
](url)
Maybe it's an issue with the first column in the mapping file here "mapping <- read_csv(here::here("2020", "2020-week52", "data", "mapglyphs-mapping.csv"))"

**Comment by victormandela** [comment]
Do I need an extra package to get the Icons loaded?

**Comment by gkaramanis** [comment]
No package but you need the Map Glyphs from here

https://mapglyphs.gumroad.com/l/mapglyphs-free
